sudo: required
language: node_js
node_js:
- node
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: us-west-2 
  app: "chef"
  env: "productionEnv"

  