sudo: required
language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm i -g npm@6.9.0

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: us-east-1 
  app: "chefcontinous"
  env: "chefcontinous-env"
  bucket_name: "elasticbeanstalk-us-east-1-805245218516"



  