 const mongoose=require('mongoose');
 const Schema = mongoose.Schema;
 




const UserSchema = new Schema({
_id: {type: String},
userName:{type: String},
userPassword: {type: String},
firstName: {type: String},
lastName: {type: String},
address: {type: String},
city: {type: String},
region: {type: String},
postalCode: {type: String},
country: {type: String},
email: {type: String},
cuisinesLikes:[String],
cuisinesDislikes:[String],
foodLikes:[String],
foodDislikes:[String],
flavorLikes:[String],
flavorDislikes:[String],
weeks:[{weekID:{type: String},weeksRecipes:{

      Monday:{Breakfast:{ title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Lunch:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Dinner:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}}},
      Tuesday:{Breakfast:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Lunch:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Dinner:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}}},
      Wednesday:{Breakfast:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Lunch:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Dinner:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}}},
      Thursday:{Breakfast:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Lunch:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Dinner:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}}},
      Friday:{Breakfast:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Lunch:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Dinner:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}}},
      Saturday:{Breakfast:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Lunch:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Dinner:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}}},
      Sunday:{Breakfast:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Lunch:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}},
            Dinner:{title: {type: String},
                        ingredients: [String],
                        method: [String],
                        picture: {type: String}}}
}}],
recipesLikes:[Object],
recipesdisLikes:[Object],
});





module.exports = mongoose.model("User", UserSchema);